remove emails from people that left Mirai
miraisolutions/ShinyCICD pull request #7
Opened 2022-01-11 09:56 UTC by Chargothrond

We need to define a new "cre" role, which should probably be @riccardoporreca .

Should I add myself as well? I didn't contribute too much to the repo, but am familiar with it.

2022-01-18 11:33 UTC, Chargothrond commented
The renv CI CD failures will be addressed in https://github.com/miraisolutions/ShinyCICD/pull/8

2022-01-18 11:56 UTC, riccardoporreca requested changes

2022-01-18 11:56 UTC, riccardoporreca commented on DESCRIPTION
> +    c(person("Peter", "Schmid", role = c("cbt", "cre"),
There is no specific reason to be "only" `cbt`
```suggestion
    c(person("Peter", "Schmid", role = c("aut", "cre"),
```

2022-02-08 08:29 UTC, riccardoporreca approved these changes
LGTM, agree on the CI issues to be addressed separately

2022-02-08 09:13 UTC, merged